//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTheVision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int id { get; set; }
        public string mName { get; set; }
        public string mGenre { get; set; }
        public string mReleaseYear { get; set; }
        public string mTime { get; set; }
        public string mCountry { get; set; }
        public string mDescription { get; set; }
        public string mTrailer { get; set; }
        public string mImdb { get; set; }
        public string mPoster { get; set; }
        public Nullable<int> type { get; set; }
    }
}
